### ISSUE TITLE
feature: Add wasm module

### ISSUE THREAD

**Issue by arnoson** [ltrujello/Hobby_Curve_Algorithm#1]
Thanks a lot for your implementations! Most of the other (Python ported) js implementations I found were really messy and complicated.

Would it be possible to create a web assembly version of your C++ implementation that exposes the `hobby_ctrl_points` function to javascript?
I have never tried web assembly, but compiling it with emscripten should be possible (https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm). If you are interested, I can take a look at it, or maybe you already are familiar with emscripten.

**Comment by arnoson** [comment]
I managed to get wasm working but the wasm module was around 50kb and the js runtime another 20kb which is a too big for a web app for me. I created a pure js [implementation](https://github.com/arnoson/hobby-curve) based on a js port of a python port I found. Thank you for providing such a clean implementation of the hobby algorithm. I used it as a reference and it helped me to understand the the hobby algorithm much better!

**Comment by ltrujello** [comment]
Sorry to get back to you quite late! I did consider making a web assembly version of the C++ to run in javascript, as that is exactly what the author of the Linear Algebra Js library I used did with their C++ code, but I never got around to it. It looks like you've tested it out and learned there are some drawbacks so that's quite interesting. 

I'll be sure to check out your js implementation and try to use it for this react app I was making that I got stuck on since I had some problems with the Linear Algebra library I was using. In any case I'm glad you found my repo useful!
